baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jessa Studio'
theme = 'ananke'

[params]
  description = "Vocal & piano lessons in Elk Grove, CA and online via Zoom."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Lessons & Rates"
  url = "/lessons/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
